"""followers

Revision ID: 144046f5b38e
Revises: 831e1c1585dd
Create Date: 2018-11-26 09:06:45.705366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144046f5b38e'
down_revision = '831e1c1585dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
