"""empty message

Revision ID: 831e1c1585dd
Revises: 9e3a6eeff381
Create Date: 2018-11-24 10:05:50.074127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e1c1585dd'
down_revision = '9e3a6eeff381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_file')
    # ### end Alembic commands ###
